# Generated by Django 2.2 on 2020-02-27 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20200227_1734'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmp', '0002_auto_20200227_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompraDet',
            new_name='ComprasDet',
        ),
    ]
